### ISSUE TITLE
Use Django 1.9.2 has two warning

### ISSUE THREAD

**Issue by sunnyrainwss** [incuna/django-wkhtmltopdf#100]
/python3.5/site-packages/wkhtmltopdf/views.py:53: RemovedInDjango110Warning: The current_app argument of TemplateResponse is deprecated. Set the current_app attribute of its request instead.
  _args, *_kwargs)

/python3.5/site-packages/wkhtmltopdf/utils.py:241: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  content = smart_text(template.render(context))

**Comment by johnraz** [comment]
> /python3.5/site-packages/wkhtmltopdf/utils.py:241: RemovedInDjango110Warning: render() must be called with a dict, not a Context. content = smart_text(template.render(context))

Should be fixed by #102 

Do you mind opening a PR for the first one?

**Comment by johnraz** [comment]
Fixed by #102 and #119
