### ISSUE TITLE
Installing django-wkhtmltopdf fails on fresh requirement install

### ISSUE THREAD

**Issue by debnet** [incuna/django-wkhtmltopdf#105]
A lot of travis like environments (like GitLab CI) always install all requirements for testing purposes and often use twelve-factor configuration with environment variables. (http://12factor.net/)

This code in will fail on install because Django is not installed yet:
https://github.com/incuna/django-wkhtmltopdf/blob/master/wkhtmltopdf/__init__.py#L2-L3

A better way must be provided to ensure the installation of the product. 
A quick-and-dirty way is to use a try/catch ImportError.

```
try:
    if 'DJANGO_SETTINGS_MODULE' in os.environ:
        from .utils import *
except ImportError:
    pass
```

**Comment by johnraz** [comment]
@luzfcb I'd accept a PR with only this specific commit right away ;-)

**Comment by johnraz** [comment]
@debnet any chance you could try out the fix made by @luzfcb ?

**Comment by debnet** [comment]
Should work. Is it inside the PyPI version?

**Comment by johnraz** [comment]
@debnet I'm gonna close this one, if you find out this is not fixed after all, please re-open ;-)

**Comment by johnfraney** [comment]
@johnraz I had this error happen to me yesterday doing a fresh install with Python 3.6 using Heroku's Python buildpack.
