### ISSUE TITLE
ProtocolUnknownError when link styles with https in a template

### ISSUE THREAD

**Issue by bertini36** [incuna/django-wkhtmltopdf#114]
Hi!

I've noticed that when I'm link a font or css in html template with https protocol in href attr your library throws me the exception ProtocolUnknownError (when call response.rendered_content). My current solution has been use http  but I think it should be able to use https.

Thanks!

**Comment by johnraz** [comment]
We will need more details in order to further investigate this. A traceback would be a good start and a pull request with a failing test case would be perfect. thx.

**Comment by bertini36** [comment]
Sorry I was trying to make a test to show the error only in your project but I did not get it. I think that it is a n integration problem with my app (only works if I use http, not https).

**Comment by johnraz** [comment]
Ok closing for now then
