### ISSUE TITLE
RemovedInDjango110Warning: current_app argument

### ISSUE THREAD

**Issue by rowanv** [incuna/django-wkhtmltopdf#116]
I'm getting the following warning about deprecation in a future version of Django:

```
RemovedInDjango110Warning: The current_app argument of TemplateResponse is deprecated. Set the current_app attribute of its request instead.
  *args, **kwargs)
```
Django version is 1.9.4 . 

Looks like this was referenced in #100, where @johnraz requested that a new issue be opened for this specifically. Couldn't find the new issue, but let me know if I'm missing it.

**Comment by johnraz** [comment]
@rowanv this should be fixed by #119, feel free to reopen if something is still wrong 😉
