### ISSUE TITLE
Generating table of content

### ISSUE THREAD

**Issue by kriwil** [incuna/django-wkhtmltopdf#12]
How to generate ToC using django-wkhtmltopdf? I checked the code but didn't see a way to do that. I might miss something.

**Comment by sikko** [comment]
Can someone please provide a code example? by default django-wkhtmltopdf calls the command:

`wkhtmltopdf [URL]`

But i need to call:

`wkhtmltopdf toc [URL]`

and "toc" can't be passed as an argument... So how am I supposed to call it?
Thanks for your help

**Comment by tclancy** [comment]
This doesn't look possible as-is: the ToC file needs to be rendered to HTML and then passed as a page. I have need for this and was thinking of creating a new option like `WKHTMLTOPDF_TOC_OPTIONS` that would accept a path to an XSL file and a position to indicate which page it should appear on. The `cover` argument could be handled in a similar fashion (aside from not needing to indicate which page that should be on), but I don't see anything specific to a cover that you can't simply do in your HTML template already.

**Comment by mittalrahul** [comment]
#136 is working fine. But it is also including Header & Footer in the Cover page.
