### ISSUE TITLE
Django 1.10 - unexpected keyword argument 'current_app'

### ISSUE THREAD

**Issue by flaudizio** [incuna/django-wkhtmltopdf#120]
Hi,

I've got this error using Django 1.10:

TypeError at
__init__() got an unexpected keyword argument 'current_app'

Exception Location:
venv/lib/python3.5/site-packages/wkhtmltopdf/views.py in __init__, line 53

My view:

response = PDFTemplateResponse(request=request, filename ="hello.pdf", template=self.template_name_pdf, context=self.context, show_content_in_browser=True)

Any suggest?

**Comment by johnraz** [comment]
This should be fixed on master

**Comment by christianbundy** [comment]
@johnraz How often are builds pushed? I'm not seeing this fix in PyPi yet.

**Comment by johnraz** [comment]
Whenever someone with the permission to do so takes the time to do it. I personally don't have that perm.

**Comment by KevinEtienne** [comment]
Thanks, it looks like the last release was a while back. I'm going to update the changelog and do a version bump.

**Comment by KevinEtienne** [comment]
I've created a new release `3.1.0`. Thank you @johnraz.

**Comment by johnraz** [comment]
awesome! thanks @KevinEtienne

**Comment by christianbundy** [comment]
@KevinEtienne Thanks for jumping on this so quickly! Thanks a ton for your work on this project.

**Comment by KevinEtienne** [comment]
In fact I haven't done any work on it it's my colleagues and most of all it's @johnraz and all the [recent contributors](https://github.com/incuna/django-wkhtmltopdf/pulls?q=is%3Apr+is%3Aclosed) :)

**Comment by christianbundy** [comment]
Well then, I take back my appreciation. 😉 

Thanks @johnraz and [everyone else](https://github.com/incuna/django-wkhtmltopdf/graphs/contributors).

**Comment by KevinEtienne** [comment]
@flaudizio can you confirm you're not having the error anymore?

**Comment by flaudizio** [comment]
@KevinEtienne Yes, all fine now. 

Thank's a lot.
Regards.
