### ISSUE TITLE
What if no access to /tmp?

### ISSUE THREAD

**Issue by gabn88** [incuna/django-wkhtmltopdf#127]
Cannot change the settings without overriding all classes :(

**Comment by gabn88** [comment]
Also, I'm having the same issue that it is pita to debug CalledProcessError..

**Comment by johnraz** [comment]
Could you please take some time to better explain your concern here.
I would like to kindly remind you that this is a community backed project and that giving proper input when facing an issue is the corner stone of getting feedback.
Please give us a clear description of your use case. Then, maybe someone will have some spare time to spend on it, maybe not. Also please do not cross reference different issue in on issue, this creates useless confusion.

**Comment by gabn88** [comment]
Sorry for the lazy issue. You are correct to say something about it.

I will try to create a pull request for better CalledProcessErrors, because in the end, that is the main issue.

**Comment by johnraz** [comment]
@gabn88 I'm gonna close this for now. If you start a PR and want to discuss it in another issue, feel free to create a new one ;-)

Thanks!
