### ISSUE TITLE
Migrate to this app

### ISSUE THREAD

**Issue by mnach** [incuna/django-wkhtmltopdf#129]
Hello everyone,

I think about use this library instead of my oun solution, but have some questions about pdf creation.

1. As I understood, wkhtmltopdf gets staticfiles from STATIC_ROOT setting.. So, It's wouldn't work if it's not exists (celery worker on different PC, or S3 storage)? 
   In my approach it gets staticfiles from URL using "sites framework". Wouldn't it be better? Is it poosible to use both ways (customised by settings)?
2. Is this app require custom wkhtmltopdf installation? I would like to rely on wkhtmltopdf installed from system repositories (debian jessie in my case), and use xvfb-run for virtual X server environment.
3. Is this app windows-compartible? My coleague develops on windows, and I have had a touble with NamedTemporaryFile on that strange OS.

**Comment by johnraz** [comment]
Hi @mnach:

1. Honestly I don't remember specifically what the limitations are with the static files, it's a bit cumbersome... If you find out your use case is not covered feel free to submit a patch to the lib and we will help getting it merged!
2. You can specify which binary you want to use, see the [doc](http://django-wkhtmltopdf.readthedocs.io/en/latest/settings.html#wkhtmltopdf-cmd)
3. Can't tell for sure, I'm afraid you will have to give it a shot yourself. Again if you find an issue come back to discuss it and we will help get it sorted.

**Comment by johnraz** [comment]
@mnach I'm gonna close this, if you need more help reopen it or create a new one 😉
