### ISSUE TITLE
WindowsError [Error 6] The handle is invalid (python 3)

### ISSUE THREAD

**Issue by SeyfertCode** [incuna/django-wkhtmltopdf#130]
Hello, i have same problem as: 
https://github.com/incuna/django-wkhtmltopdf/issues/91

but i am on python 3.4 / django 1.8.

how  update the check_output method in the file subprocess.py?

error on iis:
 `WindowsError [Error 6] The handle is invalid`
thanks

**Comment by johnraz** [comment]
I'm closing this because there is no need for a duplicate issue, it is not related to the python version.
