### ISSUE TITLE
render_to_temporary_file with footer template

### ISSUE THREAD

**Issue by nurmerey** [incuna/django-wkhtmltopdf#131]
I'm struggling to find a way to use render_to_temporary_file method and use footer template. Any help would be appreciated.

*I use render_to_temporary_file because I need to generate several files before zipping and providing it to the users to download.

**Comment by johnraz** [comment]
@nurmerey I don't understand why you'd use `render_to_temporary_file` to do that, it's an utility function that simply renders a Django template to a file, it doesn't do any work related to the PDF conversion.

You should instead use [`render_pdf_from_template`](https://github.com/incuna/django-wkhtmltopdf/blob/e7aa62484a6cbe89a3eeb155fcc8aef31d615cff/wkhtmltopdf/utils.py#L151).

It is quite straight forward to use.

**Comment by nurmerey** [comment]
@johnraz I needed to use render_to_temporary_file to fit already existing export structure of the project (I have tried all the other ways of generating pdf, including render_pdf_from_template, none of which worked). 
I found the answer to my own question thought: I call wkhtmltopdf after I receive the temp_file (from render_to_temporary), where I can add footer details to cmd_options.
`cmd_options['footer-right'] = 'Page [page] of [topage]'`

**Comment by johnraz** [comment]
Ok I'm not sure to completely follow the use case here but since you found your way out, that's great :-)
