### ISSUE TITLE
how to create pdf file and save local directory  in particular view method

### ISSUE THREAD

**Issue by RobertRajcool** [incuna/django-wkhtmltopdf#132]
instead of give pdf response,create pdf file and save local directory

**Comment by johnraz** [comment]
You can use [`render_pdf_from_template`](https://github.com/incuna/django-wkhtmltopdf/blob/e7aa62484a6cbe89a3eeb155fcc8aef31d615cff/wkhtmltopdf/utils.py#L151) and save the returned data to a file.
