### ISSUE TITLE
extending base.html - styles not applied to pdf

### ISSUE THREAD

**Issue by davideghz** [incuna/django-wkhtmltopdf#137]
Hi, I'm trying the following w/o any luck:

**urls.py**
```
urlpatterns = [
  ...
  url(r'^pdf/$', PDFTemplateView.as_view(template_name='my_template.html',
                                             filename='my_pdf.pdf'), name='pdf'),
]
```

**my_template.html**
```
{% extends "base.html" %}
{% block content %}
<h1 class="test-pdf">lorem ipsum</h1>
{% endblock %}
```

**custom.css**
```
.test-pdf {
  color: red;
}
```

**base.html**
```
{% load static %}
<!doctype html>
<html lang="it">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" type="text/css" media="all" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'prj_name/custom.css' %}" />
</head>
<body>
<!--[if lt IE 8]>
            <p class="browserupgrade">
            You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
            </p>
        <![endif]-->

{% block content %} {% endblock %}

<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
<script src="{% static 'mrp/custom.js' %}"></script>

</body>
</html>
```

If I browse http://localhost:8000/pdf/?as=html I can see all the stylings, but I lose them in the pdf (here attached as example). What am I doing wrong? If I inline all stylings, it works fine, but I'd prefer to use my custom.css file.. Thanks!

[my_pdf (1).pdf](https://github.com/incuna/django-wkhtmltopdf/files/883303/my_pdf.1.pdf)

**Comment by unrealsolver** [comment]
Check if the path ({% static 'prj_name/custom.css' %}) is correct.

**Comment by davideghz** [comment]
Hi @unrealsolver, thanks for your answer. Actually I'm wrong, and css is taken into consideration (text is formatted accordingly and it is also applying bootstrap's styling from cdn).

I still get a grey background though; any idea about that?
[my_pdf (6).pdf](https://github.com/incuna/django-wkhtmltopdf/files/885980/my_pdf.6.pdf)

**Comment by davideghz** [comment]
OK quick follow up: external CSS files are included, while project's static assets are not. I found other open issues here on github, like #103, #22, etc ..

Has anybody come out with a proper solution?

**Comment by davideghz** [comment]
damnit, got it working with a bunch of `!important` in my css everywhere a color is concerned... so my question is: are there hidden somewhere some default styling for the `PDFTemplateView` class output?
