### ISSUE TITLE
TypeError: render() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by user0007** [incuna/django-wkhtmltopdf#141]
django-wkhtmltopdf==3.1.0
Django==1.8.17

Django 1.8+ takes exactly 2 arguments `(self, context)` to the `render()` method => https://github.com/django/django/blob/stable/1.8.x/django/template/base.py#L204

So, this condition is invalid: https://github.com/incuna/django-wkhtmltopdf/blob/master/wkhtmltopdf/utils.py#L293 makes rendering failed.

**Comment by johnraz** [comment]
Hello @user0007,
Could you submit a failing test? and by the way if you found the source of the problem, why not submit a fix as well?

**Comment by johnraz** [comment]
Coud it be related to this https://github.com/incuna/django-wkhtmltopdf/pull/138/commits/d8fa17a2304efc4ad24be4332dbc7770aa99aabc ?

**Comment by user0007** [comment]
> Coud it be related to this d8fa17a ?

Yup, this should fix the error.
