### ISSUE TITLE
Add cover page in PDF

### ISSUE THREAD

**Issue by mittalrahul** [incuna/django-wkhtmltopdf#142]
How to add Cover page in PDF using django-wkhtmltopdf? I checked the documentation but didn't see a way to do that.

**Comment by johnraz** [comment]
You will probably find some information here: https://github.com/incuna/django-wkhtmltopdf/issues/12 and here https://github.com/incuna/django-wkhtmltopdf/pull/136.
I'm closing for now.

**Comment by mittalrahul** [comment]
#146 Cover page support added in this PR.

**Comment by divyanshjain217** [comment]
is it compulsory to use table of contents to be able to use cover page?
