### ISSUE TITLE
django-wkhtmltopdf on Heroku

### ISSUE THREAD

**Issue by davideghz** [incuna/django-wkhtmltopdf#143]
Hi, I think this is more related to wkhtmltopdf and heroku itself, but I think here might be a good place to link a good doc for running django-wkhtmltopdf on heroku.

I have set an additional buildpack on my heroku app:

```
heroku buildpacks:set --index 2 https://github.com/rafaelp/heroku-buildpack-wkhtmltopdf#0.12.2.1
```

then I

```
git push heroku master
```

and I get the following error
```
Counting objects: 1, done.
Writing objects: 100% (1/1), 195 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote: -----> Installing requirements with pip
remote: 
remote: -----> wkhtmltopdf app detected
remote: -----> Downloading wkhtmltopdf: http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
remote: -----> Installing wkhtmltopdf 0.12.2.1
remote: dpkg-deb: error: failed to read archive `/app/tmp/cache/wkhtmltopdf.deb': No such file or directory
remote:        Writing profile script
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 67.2M
remote: -----> Launching...
remote:        Released v14
```

Do you have any advice on running django-wkhtmltopdf on heroku?

**Comment by johnraz** [comment]
I hear the intention but this is really not the place, sorry.

**Comment by davideghz** [comment]
alright, but this is a blocking issue for anybody trying to run django-wkhtmltopdf on heroku. just a couple of tested links might help a lot. On google I found some buildpacks for heroku but none seems to work fine. I'll keep testing and I'll update this issue as reference for future users - if I will ever get it working. :/
