### ISSUE TITLE
The fix for null request in earlier Django versions produces no context processor

### ISSUE THREAD

**Issue by JoseOrtiz** [incuna/django-wkhtmltopdf#144]
Hi,
the fix for null request makes the context be treated as a Context, instead of a RequestContext, because you don't pass the request for context generation (line 304 of utils.py) at least in Django 1.8

Cheers

**Comment by johnraz** [comment]
@JoseOrtiz this seems right indeed. We are most likely missing a test for that. Would you mind adding a failing test case to expose the problem? And if you feel like finding a fix that would super cool!

**Comment by JoseOrtiz** [comment]
I've uploaded a fix with a test that fails, but testing is not my strength

**Comment by johnraz** [comment]
Hey @JoseOrtiz, than a lot for the contrib I will try to give it a look ASAP. I'm really busy lately ;-)

**Comment by johnfraney** [comment]
@johnraz I just updated one of my projects from Python 2.7 to Python 3.6 and came across this error. I tried out PR #145 and it worked well for me

**Comment by johnraz** [comment]
Cool @johnfraney, thx for the feed-back, I'm abroad for a few days but I'll make sure to review this by the end of the week!
