### ISSUE TITLE
subprocess.CalledProcessError return status -6

### ISSUE THREAD

**Issue by umarmughal824** [incuna/django-wkhtmltopdf#154]
subprocess.CalledProcessError
subprocess.CalledProcessError: Command '['/usr/bin/wkhtmltopdf', '--encoding', 'utf8', '--quiet', 'False', '/tmp/wkhtmltopdf4juup814.html', '-']' returned non-zero exit status -6

**Comment by johnraz** [comment]
Closing this. If you find the time to describe your case maybe someone will find the time to look at it.
