### ISSUE TITLE
Fix pdf download default

### ISSUE THREAD

**Issue by ghickman** [incuna/django-wkhtmltopdf#32]
The standard browser flow for this has always been to render PDF links unless a special header was passed to force the download.

In the last few years (~4 IIRC?) Chrome and Firefox (I've not used IE since 2002 so have no idea about that) have been rendering PDFs within the browser since they're a ISO format and really just markup under the hood.

We need to swap this default to not set the download header and follow what would be expected by users who are unfamiliar with the inner workings of the library.

Since this is a backwards incompatible change we'll also need to make a major release and document the change correctly.

**Comment by johnraz** [comment]
Afaik this is now an option and has been fixed.
