### ISSUE TITLE
Error 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by cheves5050** [incuna/django-wkhtmltopdf#52]
I'm trying to implement the basic example of this wrapper in my project using the url 

```
url(r'^pdf/$', PDFTemplateView.as_view(template_name='my_template.html',
                                       filename='my_pdf.pdf'), name='pdf'),
```

my settings.py

WKHTMLTOPDF_CMD_OPTIONS = {
   'quiet':True,
}
WKHTMLTOPDF_CMD = "/usr/local/bin/wkhtmltopdf/"

this is the error in the library

![wkhtmltopdf](https://cloud.githubusercontent.com/assets/7968090/3387279/7089656a-fc7c-11e3-80cd-ee4f6212bcf8.png)

**Comment by j535158420** [comment]
?
