### ISSUE TITLE
__init__() got an unexpected keyword argument 'mimetype' in python 3.4.1

### ISSUE THREAD

**Issue by keelung** [incuna/django-wkhtmltopdf#53]
TypeError at /diag/case/export/
**init**() got an unexpected keyword argument 'mimetype'
Request Method: GET
Request URL:    http://127.0.0.1:8000/diag/case/export/
Django Version: 1.7c1
Exception Type: TypeError
Exception Value:  
**init**() got an unexpected keyword argument 'mimetype'
Exception Location: D:\dev\Python\lib\site-packages\wkhtmltopdf\views.py in **init**, line 60
Python Executable:  D:\dev\Python\python.exe
Python Version: 3.4.1
Python Path:  
['D:/work/DPP/Scripts/Python/DiagnosticOnline',
 'C:\Program Files (x86)\JetBrains\PyCharm 3.1.3\helpers\pydev',
 'D:\dev\Python\lib\site-packages\soap2py-1.14-py3.4.egg',
 'D:\dev\Python\lib\site-packages\pysimplesoap-1.14-py3.4.egg',
 'D:\dev\Python\lib\site-packages\django-1.7c1-py3.4.egg',
 'D:\work\DPP\Scripts\Python\DiagnosticOnline',
 'C:\Windows\system32\python34.zip',
 'D:\dev\Python\DLLs',
 'D:\dev\Python\lib',
 'D:\dev\Python',
 'D:\dev\Python\lib\site-packages',
 'D:\dev\Python\lib\site-packages\win32',
 'D:\dev\Python\lib\site-packages\win32\lib',
 'D:\dev\Python\lib\site-packages\Pythonwin',
 'D:\dev\Python\Lib\site-packages\report_tools',
 'D:\dev\Python\Lib\site-packages\djangobower']
Server time:    星期日, 29 六月 2014 23:18:08 +0800

**Comment by eabps** [comment]
Django 1.7 HttpResponse() does not receive mimetype parameter.
http://django.readthedocs.org/en/latest/releases/1.7.html#features-removed-in-1-7
