### ISSUE TITLE
checkbox and radio inputs are bigger than with command-line

### ISSUE THREAD

**Issue by pterrien** [incuna/django-wkhtmltopdf#60]
Hi,

First, many thanks for this great project!
I'm facing a rather strange issue: PDF documents generated with *django-wkhtmltopdf* don't exactly look the same as those generated with the command line. To be more precise, checkboxes and radio buttons look bigger when using django.
Of course, I took care of comparing in the exact same conditions : same HTML input file (using the one dynamically generated in /tmp), and same command-line arguments (```--quiet --encoding utf8``` if I'm right).

Even more weird: it seems to be related to *wkhtmltopdf* upgrade a few days ago (now 0.12.1). And using either version 2.0.1 or 2.0.2 of *django-wkhtmltopdf* doesn't change anything...

As a result, I spent hours to design a document, in order to have it fit in one page, and now it is on 2 pages... :-(

I couldn't find any workaround, as CSS is useless for checkboxes and radios, and I couldn't have the --checkbox-svg options work with command-line to override the output.

I looked in the source code, but I cannot understand why ```django-wkhtmltopdf``` would create such a difference. I'm lost... do you see any explanation for this ?

Cheers

**Comment by johnraz** [comment]
This is probably due to the environment `wkhtmltopdf` is running on and most likely has nothing to do with this lib as initially stated. I think this kind of issue should be labeled with "wkhtmltopdf-binary-related" or something, reported upstream and closed here.

**Comment by johnraz** [comment]
Closing as this is very old and I made my point about it above, feel free to reopen if needs be.
