### ISSUE TITLE
PDFTemplateView: how to pass context?

### ISSUE THREAD

**Issue by unrealsolver** [incuna/django-wkhtmltopdf#66]
I have no idea how to do it. Currently I've solved it with `PDFTemplateResponse` class:

``` python
ctx = {'val': 42}
tpl = get_template('pdf/page.html')
res =  PDFTemplateResponse(
        request=request,
        template=tpl,
        context=ctx
        filename='whatever.pdf'
)
return res
```

**Comment by davideghz** [comment]
hi @mlen108 I'm still learing the basics of class based views, can you please add some more bits to show how to pass some thing like `name = 'Name'` to the template?

**Comment by umr55766** [comment]
> Your issue isn't related to `django-wkhtmltopdf`itself but to class based views in Django. Anyhow, the response is below.
> 
> First of all you'll need to use `PDFTemplateView` not `PDFTemplateResponse` class.
> 
> Next thing is that you create class that extends the original one, so it would be:
> 
> ```python
> classs MyView(PDFTemplateView):
>     def get_context_data(self, **kwargs):
>         context = super(MyView, self).get_context_data(**kwargs)
>         // your context here
>         return context
> ```

There is a typo in views.py 1st line `classs` - three `s`
