### ISSUE TITLE
Command returned non-zero exit status 1

### ISSUE THREAD

**Issue by ChillarAnand** [incuna/django-wkhtmltopdf#67]
I ran this wkhtmltopdf on commandline and it is working fine but in django-wkhtmltopdf it is not working.

Here is my view:

```
from wkhtmltopdf.views import PDFTemplateView

class PdfView(PDFTemplateView):
    template_name = 'foo.html'

   def get_context_data(self,  **kwargs):
        context = super(PdfView, self).get_context_data(**kwargs)
        context['bar'] = 'asdf'
        return context 
```

Here is the full traceback

``` python
/home/k3/.virtualenvs/pearl/local/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                response = response.render() ...
▶ Local vars
/home/k3/.virtualenvs/pearl/local/lib/python2.7/site-packages/django/template/response.py in render
            self.content = self.rendered_content ...
▶ Local vars
/home/k3/.virtualenvs/pearl/local/lib/python2.7/site-packages/wkhtmltopdf/views.py in rendered_content
                    prefix='wkhtmltopdf', suffix='.html',
                    delete=(not debug)
                )
                footer_filename = footer_file.name
            return self.convert_to_pdf(filename=input_file.name,
                                       header_filename=header_filename,
                                       footer_filename=footer_filename) ...
        finally:
            # Clean up temporary files
            for f in filter(None, (input_file, header_file, footer_file)):
                f.close()
▶ Local vars
/home/k3/.virtualenvs/pearl/local/lib/python2.7/site-packages/wkhtmltopdf/views.py in convert_to_pdf
        # Clobber header_html and footer_html only if filenames are
        # provided. These keys may be in self.cmd_options as hardcoded
        # static files.
        if header_filename is not None:
            cmd_options['header_html'] = header_filename
        if footer_filename is not None:
            cmd_options['footer_html'] = footer_filename
        return wkhtmltopdf(pages=[filename], **cmd_options) ...
    @property
    def rendered_content(self):
        """Returns the freshly rendered content for the template and context
        described by the PDFResponse.
▶ Local vars
/home/k3/.virtualenvs/pearl/local/lib/python2.7/site-packages/wkhtmltopdf/utils.py in wkhtmltopdf
    ck_args = list(chain(cmd.split(),
                         _options_to_args(**options),
                         list(pages),
                         [output]))
    ck_kwargs = {'env': env}
    if hasattr(sys.stderr, 'fileno'):
        ck_kwargs['stderr'] = sys.stderr
    return check_output(ck_args, **ck_kwargs) ...
def content_disposition_filename(filename):
    """
    Sanitize a file name to be used in the Content-Disposition HTTP
    header.
▶ Local vars
/usr/lib/python2.7/subprocess.py in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
    output, unused_err = process.communicate()
    retcode = process.poll()
    if retcode:
        cmd = kwargs.get("args")
        if cmd is None:
            cmd = popenargs[0]
        raise CalledProcessError(retcode, cmd, output=output) ...
    return output
def list2cmdline(seq):
    """
    Translate a sequence of arguments into a command line
▶ Local vars
```

**Comment by sagarpomal** [comment]
@ChillarAnand have you solved the issue? I am getting the same error.

**Comment by ChillarAnand** [comment]
@sagarpomal nope

**Comment by meshy** [comment]
Where is says `CalledProcessError: Command '['/usr/local/bin/wkhtmltopdf', '--encoding', u'utf8', '--quiet', '/tmp/wkhtmltopdf2YjISp.html', '-']' returned non-zero exit status 1`, have you tried running this command to see if you get a clearer message?

ie: `/usr/local/bin/wkhtmltopdf --encoding utf8  --quiet /tmp/wkhtmltopdf2YjISp.html -`

**Comment by meshy** [comment]
obviously the path to the html file till not be the same

**Comment by sagarpomal** [comment]
@meshy it says you need to specify  atleast one input and output file.

**Comment by sagarpomal** [comment]
@meshy $ wkhtmltopdf/bin/wkhtmltopdf --encoding utf8 --quiet c:/us
Error: Failed loading page appdata/local/etm
re this error with --load-error-handling ignore)
Exit with code 1 due to network error: ProtocolUnknownError

**Comment by meshy** [comment]
@sagarpomal that looks like this error: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1645

**Comment by sagarpomal** [comment]
@meshy Thank you for your concerns. By referring your link, i added <!doctype html>, and then executed the following cmd:
$ c:/wkhtmltopdf/bin/wkhtmltopdf --encoding utf8 --quiet C:/users/xxx/appdata/local/temp/wkhtmltopdf2olql2.html -

o/p" 
%%EOF
Exit with code 1 due to network error: ContentNotFoundError

**Comment by ka7eh** [comment]
Just had the same issue and ran the metioned command in terminal:
`wkhtmltopdf --encoding utf8 --quiet False /tmp/wkhtmltopdf_tpefbf6.html -`
and here's the response:
`Error: This version of wkhtmltopdf is build against an unpatched version of QT, and does not support more then one input document.`

**Comment by sagarpomal** [comment]
@meshy There seems to be problem with loading bootstrap.css files, it shows error : Exit with code 1 due to network error: ContentNotFoundError
But when i pass a Simple HTML file without bootstrap stylesheet and all, it works perfectly. So what should i do for that?

**Comment by sagarpomal** [comment]
@meshy It seems that the css files which are external, wkhtmltopdf is not able to generate the pdf.

**Comment by meshy** [comment]
@ka7eh I suspect that you installed the version of `wkhtmltopdf` using your package manager instead of from http://wkhtmltopdf.org/downloads.html. Try to install the binary from there.

@sagarpomal I don't know exactly what the issue is there, but I don't think it's a problem with this library. Perhaps you should open an issue on https://github.com/wkhtmltopdf/wkhtmltopdf

**Comment by sagarpomal** [comment]
@meshy i think wkhtmltopdf doesn't accept relative paths to css and other linked styles. It accepts absolute path. Any solutions?

**Comment by halfnibble** [comment]
Solution.

You MUST specify a 'STATIC_ROOT' in settings.py. It must be different from STATIC_DIRS.

Then, you have to run:
`python manage.py collectstatic`

Hope this helps.

**Comment by kurkop** [comment]
** /tmp/file.html was written src (javascript and css header) with file///

I changed in Django the STATIC_URL by default to:

    STATIC_URL = 'http://domain.com/static/'

And I use "static" in templates as recommended the official documentation https://docs.djangoproject.com/en/1.8/howto/static-files/:

    {% load staticfiles %} and {% static 'js/jquery.min.js'%}"

http://stackoverflow.com/questions/31442049/uwsgi-wkhtmltopdf-django-not-works

**Comment by luzfcb** [comment]
This issue bite me too.
In my case, i have the follow code in my template 
```
    <script>if (!window.jQuery) {
        document.write('<script src="{% static 'core/js/jquery/1.11.3/jquery.min.js' %}"><\/script>');
        document.write('<script src="{% static 'core/js/jquery/1.11.3/jquery-migrate.min.js' %}"><\/script>');
    }
    </script>
```

after render

```
    <script>if (!window.jQuery) {
        document.write('<script src="/static/core/js/jquery/1.11.3/jquery.min.js"><\/script>');
        document.write('<script src="/static/core/js/jquery/1.11.3/jquery-migrate.min.js"><\/script>');
    }
    </script>
```

**Comment by halfnibble** [comment]
This just happened to me again. This time because I deleted one of the CSS files in my static/css dir. So any missing stylesheets or scripts will generate this error.

**Comment by jpjuliao** [comment]
> Solution.
> 
> You MUST specify a 'STATIC_ROOT' in settings.py. It must be different from STATIC_DIRS.
> 
> Then, you have to run:
> `python manage.py collectstatic`
> 
> Hope this helps.

It worked for me!
