### ISSUE TITLE
 pdf does not render data from ajax requests as their urls are read relative to the file system  

### ISSUE THREAD

**Issue by jithintomz** [incuna/django-wkhtmltopdf#70]
In temp folder my html gives the following error on console
 Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///C:/myurl/asas'.

**Comment by johnraz** [comment]
I guess you don't really mind anymore, but you have to use full url's in order to make this work (and also follow recommendation in #69). Relative urls will be rewritten to point to local file so  `wkhtmltopdf` binary can actually read them.

**Comment by jithintomz** [comment]
Absolute url's causes CSRF issues.I finally had to allow CSRF requests for the required urls to make things work.

**Comment by johnraz** [comment]
Do you have any details about this CSRF issue ?

**Comment by johnraz** [comment]
Closing as missing info and also I believe #69 is covering it.
