### ISSUE TITLE
Problem with filename

### ISSUE THREAD

**Issue by fedeverdini** [incuna/django-wkhtmltopdf#71]
My view.py

class MyPDF(PDFTemplateView):
    template_name = "core/index-direct.html"
    filename = 'my_pdf.pdf'
    cmd_options = {
        'margin-top': 3
    }

   def get_context_data(self, **kwargs):
        ... some context
        return context

I get this error:

"Can't convert 'bytes' object to str implicitly" in \site-packages\wkhtmltopdf\utils.py in http_quote, line 129

I was trying to find a way to solve this, and it works form me:

112   filename = filename.replace(';', '').replace('"', '').encode()
113   return http_quote(filename)

Is it the correct way to do this??? What's wrong in my code??

**Comment by milonline-eu** [comment]
unidecode lib should be mentioned as optional dependency in documentation.

**Comment by timb07** [comment]
This still seems to be an issue; the commit linked above doesn't seem to have been released.

This is the error I'm getting with Python 3.4:

```  File "/.virtualenvs/django/lib/python3.4/site-packages/wkhtmltopdf/utils.py", line 135, in http_quote
    string = string.replace(b'\\', b'\\\\').replace(b'"', b'\\"')
TypeError: Can't convert 'bytes' object to str implicitly```
