### ISSUE TITLE
Save file to disk instead of rendering it ?

### ISSUE THREAD

**Issue by sikko** [incuna/django-wkhtmltopdf#80]
It's all in the title: Is there a way to save file to a predefined disk directory instead of rendering it?

**Comment by johnraz** [comment]
if PR #95 is merged, you could use `render_pdf_from_template` [here](https://github.com/incuna/django-wkhtmltopdf/pull/95/files#diff-36b0c981b229128ec810acc97c68d8feR122), and use its output, which is the file's content, to save it to a file.

Something like:
```
with io.open('myfile.pdf', 'wb') as f:
    f.write(render_pdf_from_template('template.html', 'header.html', 'footer.html', context))
```

**Comment by johnraz** [comment]
closing this as #95 is now merged and my solution above will answer this.
