### ISSUE TITLE
.png files not rendering in pdf

### ISSUE THREAD

**Issue by nwaxiomatic** [incuna/django-wkhtmltopdf#82]
.jpg work, however. is this a design a problem or am I missing a package?

**Comment by johnraz** [comment]
Can you please provide some more info so we could reproduce the issue?

**Comment by halfnibble** [comment]
I use PNG image files without issue. The problem could arise if the PNG files are considerably larger than the JPEG files. Try adding a delay with `'javascript-delay': 500` in the  `cmd_options` dictionary, and see if the PNG's are rendered.

**Comment by johnraz** [comment]
Closing for lack of feedback and @halfnibble stating there is no issue.
