### ISSUE TITLE
Issues #15 and #16 re-emerge with Python 3 and mod_wsgi?

### ISSUE THREAD

**Issue by powderflask** [incuna/django-wkhtmltopdf#86]
Issues #15 and #16, fixed by pull 40 (https://github.com/incuna/django-wkhtmltopdf/pull/40) has re-emerged with Python3
This is an issue of compatibility between python3.4 and mod_wsgi, and had been reported and acknowledged: GrahamDumpleton/mod_wsgi#85

Not sure yet best way to patch django-wkhtmltopdf so it can detect the condition that mod_wsgi has replace sys.stderr.  Probably with a try:  except: block.   I will offer up a pull-request once I settle on a nice solution.

**Comment by johnraz** [comment]
@powderflask , this seems to be fixed in `mod_wsgi`, is this ticket resolved ?

**Comment by powderflask** [comment]
No.  This patch (https://github.com/incuna/django-wkhtmltopdf/commit/4b73d48254749bbf08c42126f10b16ac2d71f004) resolved the issue for Python 3 / mod_wsgi < 4.4.14
However, mod_wsgi 4.4.14 + now implements TextIOWrapper interface correctly by supplying a fileno() method, but throwing IOError to indicate it is not valid.   Under new versions of mod_wsgi, even the patch above fails.
I will send a pull-request for a patch that handles all cases -- Python 2 / 3  and variants of mod_wsgi.  Sorry I didn't get to this early.

**Comment by johnraz** [comment]
ok thanks for getting back to me :-)

**Comment by powderflask** [comment]
OK -- pull request made https://github.com/incuna/django-wkhtmltopdf/pull/97  -- very minor tweak to ensure this works with mod_wsgi 4.4.14+   Thanks for the reminder -- just needed a prod :-)

**Comment by powderflask** [comment]
Oh crap!  Please discard that change -- going too fast, made request for wrong change.  Oops.

**Comment by johnraz** [comment]
Hey it's me again, back with the same question, is it ok to close this one now that #97 is merged in? cheers :-)

**Comment by powderflask** [comment]
Yeah -- close it!  Thanks johnraz, appreciate the merge.  Excellent package -- I'm trying to swing some coin your way from my client -- saved me a few hours of work on this project.
