### ISSUE TITLE
State of the project ?

### ISSUE THREAD

**Issue by johnraz** [incuna/django-wkhtmltopdf#96]
I just would like to know what is the state of this project and who is supposed to maintain it, I'm willing to put a little bit of effort in this library as pdf rendering is a PITA and having a maintained library for django is really an asset. 

@Incuna-Who, @meshy, @jturnbull, trying to ping you guys as you seem to be the latest active contributors who merged / acted on something ;-)

**Comment by maxpeterson** [comment]
Thanks @johnraz I have done some house keeping.

**Comment by johnraz** [comment]
Sweeet ! Thanks a lot :-) 

Do you plan to release something on pypi ?

**Comment by maxpeterson** [comment]
@johnraz yes, already released 2.1.0 

I have also added you as a collaborator. If you @ me directly I will  try and spend time on it or nudge someone else here.

**Comment by johnraz** [comment]
Awesome!
